// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arcora.Api.Migrations
{
    [DbContext(typeof(ArcoraDbContext))]
    partial class AddPostalLookupSuggestion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arcora.Api.Entities.PostalLookupSuggestion", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");

                    b.Property<string>("CapturedDate");

                    b.ToTable("PostalLookupSuggestions");
                });
        }
    }
}
